fonts:
  default:
    name: 'HelveticaNueueThin'
    size: 14
  bold:
    name: 'HelveticaNueueBold'
    size: 14
  header:
    name: 'HelveticaNueueBold'
    size: 16
projects:
  - title: 'Teams-API'
    links:
      - title: 'repo'
        href: 'https://github.com/InVisionApp/teams-api'
        emoji: octopus
      - title: 'pull requests'
        href: 'https://github.com/InVisionApp/teams-api/pulls'
        emoji: octopus
  - title: 'Users-API'
    links:
      - title: 'repo'
        href: 'https://github.com/InVisionApp/users-api'
        emoji: octopus
      - title: 'pull requests'
        href: 'https://github.com/InVisionApp/users-api/pulls'
        emoji: octopus
